//
// Created by heeve on 27.05.22.
//

#ifndef CUDA_MEMORY_OPTIMIZATIONS_MATRIX_MULTIPLICATION_CUH
#define CUDA_MEMORY_OPTIMIZATIONS_MATRIX_MULTIPLICATION_CUH

void coalescedMatrixMultiplication();

#endif //CUDA_MEMORY_OPTIMIZATIONS_MATRIX_MULTIPLICATION_CUH
