//
// Created by heeve on 27.05.22.
//

#ifndef CUDA_MEMORY_OPTIMIZATIONS_BATCHING_CUH
#define CUDA_MEMORY_OPTIMIZATIONS_BATCHING_CUH

void measureBatching();

#endif //CUDA_MEMORY_OPTIMIZATIONS_BATCHING_CUH
